services:
    app.cors.event_listener:
        class: ApiBundle\EventListener\CorsListener
        arguments: [ '@event_dispatcher' ]
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 10000 }

    app.json_response.handler:
        class: ApiBundle\Handler\JsonResponseHandler

    app.photo.manager:
        class: ApiBundle\Manager\PhotoManager
        arguments: [ '@doctrine.orm.entity_manager', %kernel.root_dir% ]

    app.tag.manager:
        class: ApiBundle\Manager\TagManager
        arguments: [ '@doctrine.orm.entity_manager' ]
